### ISSUE TITLE
Starting a shake in coroutines won't have any effect

### ISSUE THREAD

**Issue by ImYellowFish** [ewersp/CameraShake#1]
Seems like it is caused by GetT() functions in CameraShake.cs.

m_startTime gets initiated in Start(). However in a coroutine it seems that GetT() will be called before initiation. So the shake would be considered complete, and deleted in the next frame.

Setting m_startTime in ctor solves the problem.

**Comment by ewersp** [comment]
Ah, good catch! I changed initialization from Start() to Awake() which seemed to fix the issue in my test driver:

`	IEnumerator StartDelayed() {
		yield return new WaitForSeconds(1.0f);
		CameraShakeManager.Instance.Play("Camera Shakes/Default");
	}`

 Thanks.
